package com.flowboard.app.enums;

public enum ActivityType {

    PROJECT_CREATED,
    PROJECT_UPDATED,

    BOARD_CREATED,
    BOARD_UPDATED,

    COLUMN_CREATED,
    COLUMN_UPDATED,
    COLUMN_MOVED,
    COLUMN_DELETED,

    CARD_CREATED,
    CARD_UPDATED,
    CARD_STARTED,
    CARD_MOVED,
    CARD_ASSIGNED,
    CARD_UNASSIGNED,
    CARD_REASSIGNED,
    CARD_COMPLETED,
    CARD_REOPENED,
    CARD_DELETED,

    MEMBER_ADDED,
    MEMBER_REMOVED,

}
